```{r}

library(rtweet)
library(streamR)
library(ndjson)
library(ROAuth)
library(tidyverse)
library(stringr)
library(dplyr)
library(rworldmap)
library(RColorBrewer)
library(fields)
library(ggplot2)
library(ggthemes)
library(ggmap)
library(lubridate)
library(countrycode)
library(viridis)
library(ggpubr)
library(readr) 
library(data.table)
library(delabj)
library(patchwork)
```

```{r}
twitter_token <- create_token(app = "x",
                              consumer_key = "x",
consumer_secret = "x",
access_token = "x",
access_secret = "x")
```

#```{r, cache=TRUE}
consumer_key <- "x"
consumer_secret <- "x"
access_token <- "x"
access_secret <- "x"
my_oauth <- setup_twitter_oauth(
  consumer_key, consumer_secret, access_token, access_secret)
load("~/my_oauth")
#```

```{r}
leg_dets <- 'https://theunitedstates.io/congress-legislators/legislators-current.csv'

twitters <- read.csv((url(leg_dets)),
                     stringsAsFactors = FALSE) %>%
  #filter(type == 'rep') %>% # & twitter!=''
  rename (state_abbrev = state,
          district_code = district)
```


```{r}
congress_tweets <- rtweet::get_timeline( 
  twitters$twitter, 
  n = 1000) %>%
  mutate(created_at = as.Date(gsub(' .*$', '', 
                                   created_at))) %>%
  filter(is_quote == 'FALSE' & 
           is_retweet == 'FALSE' & 
           created_at >= '2020-03-01' &
           display_text_width > 0)
```

```{r}
#congress_tweets2 = data.frame(lapply(congress_tweets, as.character), stringsAsFactors=FALSE)
#write.csv(congress_tweets2, file = "congress_tweets.csv", row.names = FALSE)
```

```{r}
congress_tweets <- suppressWarnings(read_csv("congress_tweets.csv", na = "NULL"))
```

```{r}
#Then we join the two data sets. And calculate total tweets generated by members of Congress by party affiliation in 2020.

congress_tweets1 <- congress_tweets %>%
  mutate(twitter = toupper(screen_name)) %>%
  select(status_id, created_at, twitter, text) %>%
  inner_join(twitters %>% mutate(twitter = toupper(twitter)))


all_tweets <- congress_tweets1 %>%
  group_by(created_at, party) %>%
  summarise(ts = n()) %>%
  rename(date = created_at)
```

```{r}
#Also, Democrats do tweet more, but they also have numbers at present. And it seems that members of Congress put their phones down a bit on the weekends.

all_tweets %>%
  filter(party != 'Independent') %>% # Justin Amash & Bernie Sanders & Angus King
  ggplot() +
  geom_line(aes(x = date, 
                y= ts, 
                color = party
                ),
            size = .8) +
  #theme_minimal() +
  theme_delabj() +
  #delabj::scale_color_zune() +
  ggthemes::scale_color_stata(name = "") +
  theme(text = element_text(family="ITC Officina Sans LT Book"),
         axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_date(date_breaks = '1 week', date_labels = "%b %d") +
  theme(legend.position = 'top',
        plot.title = element_text(vjust = 1.5, size = 15, family="ITC Officina Sans LT Bold"),
        plot.caption = element_text(hjust = -0.1))  +
  labs(x = "", y = "",
    title = 'Total congressional tweets by party affiliation',
    caption = "Source: Data collected from Twitter's REST API via rtweet\n     www.fishwongy.com")
```

#2019 NOVEL CORONAVIRUS & lexical variation
```{r}
pan <- 'pandemic|'
cv <- 'coronavirus|corona virus|'
covid <- 'covid19|covid|covid 19|covid-19|'
cvp <- 'blacklivesmatter'
searches <- paste0(pan, cv, 
                   covid, cvp)
```

```{r}
covid_tweets <- lapply(1:nrow(congress_tweets1), function(x) {
  
    spots <- gregexpr(pattern = searches, congress_tweets1$text[x], ignore.case=TRUE)
    covid_gram <- regmatches(congress_tweets1$text[x], spots)[[1]] 

    if (-1 %in% spots){} else {
      data.frame(doc_id = congress_tweets1$status_id[x],
                 date = congress_tweets1$created_at[x],
                 twitter = congress_tweets1$twitter[x],
                 party = congress_tweets1$party[x],
                 covid_gram = covid_gram,
                 stringsAsFactors = FALSE)}  })  %>% 
  data.table:::rbindlist() 
```

```{r}
covid_tweets <- covid_tweets %>%
  mutate(covid_gram = tolower(covid_gram),
         covid_gram = ifelse(grepl('covid', covid_gram), 'covid19', covid_gram),
         covid_gram = ifelse(grepl('corona virus', covid_gram), 'coronavirus', covid_gram))

covid_tweets %>% sample_n(10) %>% select(-doc_id) %>%knitr::kable()
```

#Rates of reference to 2019 NOVEL CORONAVIRUS
```{r}
all <- covid_tweets %>%
  group_by(date) %>%
  summarize(n = n()) %>%
  left_join(all_tweets %>% group_by(date) %>% summarise(ts = sum(ts))) %>%
  mutate(per = n/ts,
         covid_gram = 'total') %>%
  select(date, covid_gram, n:per)

```


```{r}
total <- 
  covid_tweets %>%
  group_by(date, covid_gram) %>% #,party,   
  summarize(n = n()) %>%
  left_join(all_tweets %>% group_by(date) %>% summarise(ts = sum(ts))) %>%
  mutate(per = n/ts) %>%
  bind_rows(all) %>%
  
  ggplot() +
  geom_line(aes(x = date, 
                y= per, 
                color = covid_gram
                ), size = .8
            ) +
  theme_delabj() +
  #ggthemes::scale_color_tableau(palette = "Miller Stone") +
  scale_color_hp_d(option = "RonWeasley2", name = "",
                   breaks = c("total", "coronavirus", "covid19", "pandemic", "blacklivesmatter"),
                   label = c("Total", "Coronavirus", "Covid19", "Pandemic", "Blacklivesmatter"))+
  #delabj::scale_color_delabj() +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8), labels = c(0, 0.2, 0.4, 0.6, 0.8)) +
  theme(legend.position = c(0.14, 1.08), #0.74, 0.95
        legend.direction = "horizontal",
        legend.key.size = unit(0.3, "cm"),
        legend.text=element_text(size=12),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.y = element_text(size = 12),
        text = element_text(size = 9.5, family="ITC Officina Sans LT Book"),
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        strip.text = element_text(size=12),
        plot.title = element_text(vjust = 1.5, size = 18, face = "bold", family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0, vjust = 2, size= 15, family="ITC Officina Sans LT Book"),
        plot.caption = element_text(hjust = -0.12, size = 7, family="ITC Officina Sans LT Book")) +
  scale_x_date(date_breaks = '5 days', date_labels = "%b %d") +
  labs(y = "Daily reference rate\n",
       x = "",
       title = 'Reference rates to different topics by party affiliation',
       subtitle = 'Among US Senators & House Representatives\n\n',
       caption = "") #Source: Data collected from Twitter's REST API via rtweet\n      www.fishwongy.com

total
```

```{r}
party <- 
  covid_tweets %>%
  group_by(date, party, covid_gram) %>% #,party,   
  summarize(n = n()) %>%
  left_join(all_tweets) %>%
  mutate(per = n/ts) %>%
  
  filter(party != 'Independent') %>%
  ggplot() +
  geom_line(aes(x = date, 
                y= per, 
                color = covid_gram
                ),
            size = .7) +
  theme_delabj() +
  #delabj::scale_color_delabj() +
  #ggthemes::scale_color_tableau(palette = "Miller Stone") +
  scale_color_hp_d(option = "RonWeasley2", name = "",
                   breaks = c("total", "coronavirus", "covid19", "pandemic", "blacklivesmatter"),
                   label = c("Total", "Coronavirus", "Covid19", "Pandemic", "Blacklivesmatter")) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5), labels = c(0, 0.1, 0.2, 0.3, 0.4, 0.5),
                     sec.axis = dup_axis()) +
  theme(#legend.position = c(0.155, 1.18), #0.74, 0.95
        #legend.direction = "horizontal",
        #legend.key.size = unit(0.3, "cm"),
        legend.position = "top",
        legend.text=element_text(size=12),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 90, hjust = 1),
        text = element_text(size = 9.5, family="ITC Officina Sans LT Book"),
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        strip.text = element_text(size = 12, family="ITC Officina Sans LT Bold"),
        plot.title = element_text(vjust = 1.5, size = 15, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(vjust = 2,  size = 10, family="ITC Officina Sans LT Book"),
        plot.caption = element_text(hjust = -0.07, size = 13, family="ITC Officina Sans LT Book")) +
  scale_x_date(date_breaks = '1 week', date_labels = "%b %d") +
  facet_wrap(~party) +
  labs(x = "",
       y = "",
       #title = '',#Reference rates to different topics by party affiliation
       #subtitle = '', #Among US Senators & House Representatives'n'n
       caption = "Source: Data collected from Twitter's REST API via rtweet\n   www.fishwongy.com") 

party
```

```{r}
total/ party + 
   ggsave("tw_patch.png", dpi = 320, width = 12.8, height = 12)
```




#Extract blm tweets
```{r}
blm <- congress_tweets1[grep("blacklives?|black lives?", congress_tweets1$text, ignore.case = T), ]
```

```{r}
library(quanteda)
```

```{r}
text_corpus <- corpus(blm, text_field = "text")
```

```{r, fig.height=5}
text_corpus  %>%
    dfm(remove = c(stopwords("english"), "hongkong", "hong", "kong", "protests", "weeks", "mr", "ms", "yesterday", "said", "also", "and", "32", "can", "set", "two", "since", "took", "well"), remove_punct = TRUE, remove_numbers = TRUE, remove_separators = FALSE) %>%
    dfm_trim(verbose = FALSE) %>%
    textplot_wordcloud(color = rev(RColorBrewer::brewer.pal(10, "RdBu")), rotation = 0)
```

####To extract ht and its freq
```{r}
ht <- str_extract_all(congress_tweets1$text, "#[A-Za-z0-9_]+")
ht <- unlist(ht)
head(sort(table(ht), decreasing = TRUE))
ht <- as.data.frame(sort(table(ht), decreasing = FALSE))
ht <- ht %>% filter(Freq > 100)
```

#Extract corona tweets
```{r}
corona <- congress_tweets1[grep("corona?|covid?", congress_tweets1$text, ignore.case = T), ]
```

```{r}
corona_corpus <- corpus(corona, text_field = "text")
```


```{r, fig.height=5}
corpus_subset(corona_corpus, 
              party %in% c("Democrat", "Independent", "Republican")) %>%
    dfm(groups = "party", remove = c(stopwords("english"), "hongkong", "hong", "kong", "protests", "weeks", "mr", "ms", "yesterday", "said", "also", "and", "32", "can", "set", "two", "since", "took", "well"), remove_punct = TRUE, remove_numbers = TRUE, remove_separators = FALSE) %>%
    dfm_trim(min_termfreq = 120, verbose = FALSE) %>%
    textplot_wordcloud(comparison = TRUE, color = c("royalblue4", "#83B692", "red3"), rotation = 0)
```
