```{r}
library(tidyverse)
library(ggbeeswarm)
library(extrafont)
```

```{r}
# Get the Data ------
firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')
science <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/science.csv')
```

```{r}
## Clean up data ------
## make gender and category factors
firsts <- firsts %>% 
  mutate_at(c("gender", "category"), as.factor) %>% 
  mutate(decade = year - year %% 10) %>%
  mutate(gender = case_when(str_detect(gender, "African-American Firsts") ~ "Male", TRUE~"Female"))
```

```{r, fig.height=12, fig.width=24}
# Count of firsts
firsts %>% 
  ggplot(aes(decade, fill = category)) +
  geom_rect(mapping = aes(xmin = 1945, xmax = 1965, ymin = 0, ymax = 64.3), fill = NA, color = "#C2C2C2", linetype = 3) + ## dotted outline of 50s-60s
  geom_bar() +
  
  scale_y_continuous(expand = expansion(0,0)) +
  scale_x_continuous(breaks = seq(from = 1730, to =2010, by = 10), labels = paste0(seq(1730, 2010, by = 10), "s"), expand = expansion(0,0)) +
  scale_fill_paletteer_d("dutchmasters::view_of_Delft") +
  
  geom_curve(aes(x = 1739, y = 13, xend = 1730, yend = 1.5), size = 0.5,  ## 1738 arrow
             arrow = arrow(length = unit(0.2, "inch")), 
             curvature = 0.4, color = "#F5F5F5") +
  geom_curve(aes(x = 1915, y = 53, xend = 1942, yend = 58.5), size = 0.5, ## civil rights movement arrow
             arrow = arrow(length = unit(0.2, "inch")), 
             curvature = -0.3, color = "#F5F5F5") +
  geom_rect(mapping = aes(xmin = 1969, xmax = 2001, ymin = 55, ymax = 65), fill = "#525252", color = "#525252") +  ## background of the post civil rights annotation
  annotate("text", x = 1740, y = 13, label = "1738:\nFirst free African-American community,\nGracia Real de Santa Teresa de Mose in Florida", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1855, y = 30, label = "1865:\nRatification of\nthe 13th Amendment,\nAbolishment of slavery", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1895, y = 50, label = "1950s-1960s:\nCivil Rights Movement", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1970, y = 60, label = "Post Civil Rights Era:\nGreater political\nrepresentation", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 6, color = "#F5F5F5") +
  
  labs(title = "Achievements by African Americans Throughout History\n", 
       subtitle = "Number of Achievements",
       x = "", y = "",
       caption = "Data: Tidy Tuesday\nwww.fishwongy.com") +
  theme_delabj_dark() +
  theme(text = element_text(family = "IBM Plex Sans SemiBold", size = 13),
                      title = element_text("IBM Plex Sans SemiBold", size = 24),
                      plot.title = element_text("IBM Plex Sans SemiBold", size = 32),
                      plot.title.position = "plot",
                      plot.subtitle = element_text("IBM Plex Sans SemiBold", size = 20),
                      plot.caption = element_text(size = 14),
                      axis.text = element_text(size = 14, color = "#F5F5F5"),
                      #axis.text.x = element_blank(),
                      axis.line.x = element_line(color = "#F5F5F5"),
                      axis.line.y = element_line(color = "#F5F5F5"),
                      #axis.line.x = element_blank(),
                      #axis.line.y = element_line(color = "gray80"),
                      #panel.grid = element_blank(),
                      legend.text = element_text(size = 21, family = "IBM Plex Sans Medium"),
                      legend.title = element_blank(),
                     # legend.background = element_rect(fill = "#525252", color = "#525252"),
                      plot.margin = margin(20, 20, 20, 20),
                      panel.grid.major.x = element_blank(),
                      panel.grid.minor.x = element_blank(),
                     # panel.grid.major.y = element_line(color = "gray70"),
                      panel.grid.minor.y = element_blank(),
                      #plot.background = element_rect(fill = "#525252", color = "#525252"),
                      legend.position = c(.2, .785)) +
  ggsave("black-achievements.png", width = 24, height = 12, dpi = 320) +
NULL
```

```{r, fig.height=12, fig.width=24}
# Count of firsts
firsts %>% 
  ggplot(aes(decade, fill = gender)) +
  geom_rect(mapping = aes(xmin = 1945, xmax = 1965, ymin = 0, ymax = 64.3), fill = NA, color = "#C2C2C2", linetype = 3) + ## dotted outline of 50s-60s
  geom_bar() +
  
  scale_y_continuous(expand = expansion(0,0)) +
  scale_x_continuous(breaks = seq(from = 1730, to =2010, by = 10), labels = paste0(seq(1730, 2010, by = 10), "s"), expand = expansion(0,0)) +
  #scale_fill_paletteer_d("dutchmasters::view_of_Delft") +
  scale_fill_manual(name = "", values = c("#83B692", "#721121"),
                    breaks = c("Male", "Female"))+
  
  geom_curve(aes(x = 1739, y = 13, xend = 1730, yend = 1.5), size = 0.5,  ## 1738 arrow
             arrow = arrow(length = unit(0.2, "inch")), 
             curvature = 0.4, color = "#F5F5F5") +
  geom_curve(aes(x = 1915, y = 53, xend = 1942, yend = 58.5), size = 0.5, ## civil rights movement arrow
             arrow = arrow(length = unit(0.2, "inch")), 
             curvature = -0.3, color = "#F5F5F5") +
  geom_rect(mapping = aes(xmin = 1969, xmax = 2001, ymin = 55, ymax = 65), fill = "#525252", color = "#525252") +  ## background of the post civil rights annotation
  annotate("text", x = 1740, y = 13, label = "1738:\nFirst free African-American community,\nGracia Real de Santa Teresa de Mose in Florida", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1855, y = 30, label = "1865:\nRatification of\nthe 13th Amendment,\nAbolishment of slavery", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1895, y = 50, label = "1950s-1960s:\nCivil Rights Movement", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1970, y = 60, label = "Post Civil Rights Era:\nGreater political\nrepresentation", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 6, color = "#F5F5F5") +
  
  labs(title = "Achievements by African Americans Throughout History by Gender\n", 
       subtitle = "Number of Achievements",
       x = "", y = "",
       caption = "Data: Tidy Tuesday\nwww.fishwongy.com") +
  theme_delabj_dark() +
  theme(text = element_text(family = "IBM Plex Sans SemiBold", size = 13),
                      title = element_text("IBM Plex Sans SemiBold", size = 24),
                      plot.title = element_text("IBM Plex Sans SemiBold", size = 32),
                      plot.title.position = "plot",
                      plot.subtitle = element_text("IBM Plex Sans SemiBold", size = 20),
                      plot.caption = element_text(size = 14),
                      axis.text = element_text(size = 14, color = "#F5F5F5"),
                      #axis.text.x = element_blank(),
                      axis.line.x = element_line(color = "#F5F5F5"),
                      axis.line.y = element_line(color = "#F5F5F5"),
                      #axis.line.x = element_blank(),
                      #axis.line.y = element_line(color = "gray80"),
                      #panel.grid = element_blank(),
                      legend.text = element_text(size = 21, family = "IBM Plex Sans Medium"),
                     # legend.background = element_rect(fill = "#525252", color = "#525252"),
                      plot.margin = margin(20, 20, 20, 20),
                      panel.grid.major.x = element_blank(),
                      panel.grid.minor.x = element_blank(),
                     # panel.grid.major.y = element_line(color = "gray70"),
                      panel.grid.minor.y = element_blank(),
                      #plot.background = element_rect(fill = "#525252", color = "#525252"),
                     legend.position = c(.2, .785)) +
  ggsave("black-achievements_gender.png", width = 24, height = 12, dpi = 320) +
NULL
```


```{r}
genderblack <- firsts %>% 
               group_by(category, gender) %>% 
               count(category,gender) %>%
               ungroup() %>% 
               mutate(category = fct_reorder(category, n)) %>%
               mutate(gender = case_when(str_detect(gender, "African-American Firsts") ~ "Male", TRUE~"Female"))
  
```

```{r}
genderblack %>%
ggplot(aes(x = category, y = n, fill = gender)) + 
  geom_col(position = "dodge")+
  theme_delabj_dark() + 
  scale_fill_manual(name = "", values = c("#83B692", "#721121"),
                    breaks = c("Male", "Female"))+
  scale_y_continuous(position = "right") +
  theme(legend.position = c(-0.04, 1.035),
        legend.direction = "horizontal",
        legend.key.size = unit(0.3, "cm"),
        legend.text=element_text(size = 22),
        text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
       axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 13),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 24, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 15),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 15)) +
  labs(x = "", y = "", 
       title = "Achievements by African Americans by Gender and Catagory\n",
       caption = "Data: Tidy Tuesday\nwww.fishwongy.com") +
    coord_flip() +
  ggsave("black-gender.png", width = 18, height = 10, dpi = 320) +
NULL
```

```{r}
gender <- firsts %>%
  group_by(decade, gender) %>% 
               count(decade,gender) %>%
               ungroup() %>%
  mutate_at(c("gender"), as.factor)
```


```{r}
gender %>% 
  ggplot(aes(x = decade, y = n, fill = gender)) +
  geom_rect(mapping = aes(xmin = 1945, xmax = 1965, ymin = 0, ymax = 64.3), fill = NA, color = "#C2C2C2", linetype = 3) + ## dotted outline of 50s-60s
  geom_col() + 
  scale_y_continuous(expand = expansion(0,0)) +
  scale_x_continuous(breaks = seq(from = 1730, to =2010, by = 10), labels = paste0(seq(1730, 2010, by = 10), "s"), expand = expansion(0,0)) +
  #scale_fill_paletteer_d("dutchmasters::view_of_Delft") +
  scale_fill_manual(name = "", values = c("#83B692", "#721121"),
                    breaks = c("Male", "Female"))+
  
  geom_curve(aes(x = 1739, y = 13, xend = 1730, yend = 1.5), size = 0.5,  ## 1738 arrow
             arrow = arrow(length = unit(0.2, "inch")), 
             curvature = 0.4, color = "#F5F5F5") +
  geom_curve(aes(x = 1915, y = 53, xend = 1942, yend = 58.5), size = 0.5, ## civil rights movement arrow
             arrow = arrow(length = unit(0.2, "inch")), 
             curvature = -0.3, color = "#F5F5F5") +
  geom_rect(mapping = aes(xmin = 1969, xmax = 2001, ymin = 55, ymax = 65), fill = "#525252", color = "#525252") +  ## background of the post civil rights annotation
  annotate("text", x = 1740, y = 13, label = "1738:\nFirst free African-American community,\nGracia Real de Santa Teresa de Mose in Florida", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1855, y = 30, label = "1865:\nRatification of\nthe 13th Amendment,\nAbolishment of slavery", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1895, y = 50, label = "1950s-1960s:\nCivil Rights Movement", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 7, color = "#F5F5F5") +
  annotate("text", x = 1970, y = 60, label = "Post Civil Rights Era:\nGreater political\nrepresentation", 
           hjust = 0, family = "IBM Plex Sans Medium", fontface = "italic", size = 6, color = "#F5F5F5") +
  
  labs(title = "Achievements by African Americans Throughout History by Gender\n", 
       subtitle = "Number of Achievements",
       x = "", y = "",
       caption = "Data: Tidy Tuesday\nwww.fishwongy.com") +
  theme_delabj_dark() +
  theme(text = element_text(family = "IBM Plex Sans SemiBold", size = 13),
                      title = element_text("IBM Plex Sans SemiBold", size = 24),
                      plot.title = element_text("IBM Plex Sans SemiBold", size = 32),
                      plot.title.position = "plot",
                      plot.subtitle = element_text("IBM Plex Sans SemiBold", size = 20),
                      plot.caption = element_text(size = 14),
                      axis.text = element_text(size = 14, color = "#F5F5F5"),
                      #axis.text.x = element_blank(),
                      axis.line.x = element_line(color = "#F5F5F5"),
                      axis.line.y = element_line(color = "#F5F5F5"),
                      #axis.line.x = element_blank(),
                      #axis.line.y = element_line(color = "gray80"),
                      #panel.grid = element_blank(),
                      legend.text = element_text(size = 21, family = "IBM Plex Sans Medium"),
                     # legend.background = element_rect(fill = "#525252", color = "#525252"),
                      plot.margin = margin(20, 20, 20, 20),
                      panel.grid.major.x = element_blank(),
                      panel.grid.minor.x = element_blank(),
                     # panel.grid.major.y = element_line(color = "gray70"),
                      panel.grid.minor.y = element_blank(),
                      #plot.background = element_rect(fill = "#525252", color = "#525252"),
                     legend.position = c(.2, .785))
```




#WOMEN ACHIEVMENT

```{r}
# Get the data
firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')
```

```{r}
female_firsts <- firsts %>%  
  mutate(decade = year - year %% 10) %>% # add decade values
  filter(gender=="Female African American Firsts") %>%
  filter(!(year == 1760)) %>% # Remove Jupiter Hammon (error)
  group_by(decade) %>%
  arrange(category) %>% # arrange categories for bar graph
  mutate(category = recode(category,
                           "Social & Jobs" = "Social\n& Jobs",
                           "Education & Science" = "Education\n& Science")) %>%
  mutate(index = row_number()) %>%
  ungroup()
```

```{r}
ggplot(female_firsts, aes(x=decade, y=1, group = index, fill=category)) +
  
  geom_bar(stat="identity",size=1.1, width=10,color="#343E48") +
  
  # color and key stuff
  #scale_fill_brewer(palette = "Paired", guide = guide_legend(direction = "horizontal", nrow = 2)) +
  scale_fill_paletteer_d("dutchmasters::view_of_Delft", guide = guide_legend(direction = "horizontal", nrow = 2)) +
  # x axis labels
  scale_x_continuous(name = "Decade",
                   breaks = seq(1770, 2010, by = 10),
                   labels = paste0(seq(1770, 2010, by = 10), "s"),
                   expand = c(0, 1)) +
  
  
  #add line and label for 13th amendment
  geom_segment(x=1860, y=0, xend=1860, yend=15, #1865 didn't line up right
             linetype="dotted", color="#FFF5EE") +
  
  annotate(geom = "text",
           x=1859,y=5.3,
           hjust=0, vjust=0,
           label="December 18, 1865: \nAdoption of the 13th Amendment",
           size=3.5, lineheight=.8,
           color="#F5F5F5",
           family = "IBM Plex Sans Medium", fontface = "italic",
           angle=90) +
  
  # add line and label for 19th amendment
  geom_segment(x=1916, y=0, xend=1916, yend=15, # 1920 didn't line up right
               linetype="dotted", color="#FFF5EE") +
  
  annotate(geom = "text",
           x=1915,y=5.3,
           hjust=0, vjust=0,
           label="August 26, 1920: \nAdoption of the 19th Amendment",
           size=3.5, lineheight=.8,
           color="#F5F5F5",
           family = "IBM Plex Sans Medium", fontface = "italic",
           angle = 90) +
  
  labs(title = "Achievements of Black Women in America",
       caption="Source: Tidy Tuesday\nwww.fishwongy.com") +
  theme_delabj_dark() +
  # theme stuff
  theme(#plot.background = element_rect(fill="#FFF5EE", color = "#FFF5EE"),
        #panel.background = element_rect(fill="#FFF5EE", color = "#FFF5EE"),
        text = element_text(family = "IBM Plex Sans SemiBold", size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(hjust=2, vjust=3,
                                   family = "IBM Plex Sans SemiBold",
                                   size=8, angle=50),
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(.7,"cm"),
        legend.position = c(0.2, 0.95),
        legend.text = element_text(size = 8),
        legend.title = element_blank(),
        #legend.background = element_rect(fill="#FFF5EE", color = "#FFF5EE"),
        plot.caption = element_text(#color="#A9A9A9",
                                    size = 10,
                                    family = "IBM Plex Sans SemiBold")) +

  # add line and label for achievements
  # Phillis Wheatley
  geom_curve(x = 1770, y = 9, 
             xend = 1769, yend = 1,
             curvature = 0.1,
             size=0.6, color="#FFF5EE") +

  annotate(geom="text",
           x = 1765, y = 10.5,
           hjust = 0,
           label="Phillis Wheatley",
           size=4, lineheight=.8,
           family = "IBM Plex Sans Medium", fontface = "italic",
           color="#FFF5EE"
           ) +
  annotate(geom="text",
           x = 1765, y = 9.85,
           hjust=-0.02,
           label="First African American Woman\nTo Publish a Book, 1773",
           size=2.5, lineheight=.8,
           family = "IBM Plex Sans Medium", fontface = "italic",
           color="#FFF5EE"
           ) +

# Dr. Rebecca Davis Lee Crumpler
geom_curve(x = 1870, y = 8.9, 
           xend = 1865.5, yend = 4.5,
           curvature = -0.1,
           size=0.6, color="#FFF5EE") +
  
  annotate(geom="text",
           x = 1865, y = 10.5,
           hjust=0,
           label="Dr. Rebecca Davis \nLee Crumpler",
           size=4, lineheight=.8,
           family = "IBM Plex Sans Medium", fontface = "italic",
           color="#FFF5EE"
           ) +
  annotate(geom="text",
           x = 1865, y = 9.6,
           hjust=-0.02,
           label="First African American \nWoman to Earn An M.D., 1864",
           size=2.5, lineheight=.8,
           family = "IBM Plex Sans Medium", fontface = "italic",
           color="#FFF5EE"
           ) +


# Condoleezza Rice
geom_curve(x = 1955, y = 13, 
           xend = 1995, yend = 11.4,
           curvature = 0.1,
           size=0.6, color="#FFF5EE") +
  
  annotate(geom="text",
           x = 1925, y = 14.3,
           hjust=0,
           label="Condoleezza Rice",
           size=4, lineheight=.8,
           family = "IBM Plex Sans Medium", fontface = "italic",
           color="#FFF5EE"
           ) +
  annotate(geom="text",
           x = 1925, y = 13.5,
           hjust=-0.02,
           label="First African American Woman \nto Become Secretary of State,\n 2005",
           size=2.5, lineheight=.8,
           family = "IBM Plex Sans Medium", fontface = "italic",
           color="#FFF5EE"
           ) +
  ggsave("female-african-american-achievements.png", width=9.57, height=6.92, dpi=320)  
```
