```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(lubridate)
library(scales)
library(readr)
library(quanteda)
library(delabj)
library(ggtext)
library(ghibli)
library(patchwork)
#library(cowplot)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(rgeos)
# library(geonames)
# library(countrycode)
library(rworldmap)
library(patchwork)
library(ggtext)
library(paletteer)
```

```{r}
astronauts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')
```

```{r}
p1 <-
ggplot(astronauts, aes(y = total_hrs_sum, x = year_of_mission)) +
  geom_boxplot(aes(group = year_of_mission),
               outlier.colour = "#FFD900",
               outlier.alpha = .6,
               color = "#343E48",
               fill = "lightgrey") +
  geom_smooth(method = "gam", color = "#FFD900") +
  scale_x_continuous(breaks = seq(from = 1960, to = 2020, by = 10), labels = paste0(seq(1960, 2020, by = 10), "s")) +
  labs(x = "", y = "",
       title = "Increase of Hours Spent on a Mission Over Year",
       subtitle = "Hours spent on mission") +
  theme_delabj_dark()+
  theme(text = element_text(family="ITC Officina Sans LT Book"),
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(family="ITC Officina Sans LT Bold"),
        axis.text.y = element_text(family="ITC Officina Sans LT Bold"),
        #axis.title=element_text(size=20),
        plot.title = element_text(family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0, vjust = -3, family="ITC Officina Sans LT Book"),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, family="ITC Officina Sans LT Book"))

p1
```

#Origin of the astronauts.
```{r}
countries <- astronauts %>%
              group_by(nationality, sex) %>%
              count(nationality, sex)%>%
              ungroup() %>% 
              mutate(nationality = recode(nationality,
                              "Czechoslovakia" = "Slovakia",
                              "Hungry" = "Hungary",
                              "Malysia" = "Malaysia",
                              "Netherland" = "Netherlands",
                              "U.S.S.R/Russia" = "Russia",
                              "U.S.S.R/Ukraine" = "Ukraine",
                              "Korea" = "South Korea",
                              "Republic of South Africa" = "South Africa",
                              "U.K." = "United Kingdom",
                              "U.S." = "United States of America",
                              "UAE" = "United Arab Emirates")) %>%
            filter(nationality != "U.K./U.S.") %>%
            rename("ctry_name" = "nationality",
                   "nr_of_astros" = "n")

countries
```

# get centroids
```{r}
wmap <- getMap(resolution="high")
centroids <- gCentroid(wmap, byid=TRUE)
```

# get a data.frame with centroids
```{r}
df <- data.frame(centroids)
d <- cbind(rownames(df), data.frame(df, row.names = NULL))
colnames(d) = c("ctry_name", "x", "y")
```

#join df on countries
```{r}
countries_geo <- left_join(countries, d, by = "ctry_name")
countries_geo_sf <- sf::st_as_sf(countries_geo, coords = c("x","y"))
st_crs(countries_geo_sf) = 4326
```

#world map with countries of origin highlighed with centroid points
```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
```

```{r}
map <-
  ggplot() +
  geom_sf(data = world, fill = "grey", color = "#343E48") +
  geom_sf(data = countries_geo_sf, color = "#FFD900", size = 1) +

  geom_sf(data = countries_geo_sf, color = "#FFD900", size = 3, alpha = .5) +
  geom_sf(data = countries_geo_sf, color = "#FFD900", size = 5, alpha = .2) +
  labs(title = "Astronaut's Countries of Origin")+
  coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs ") +
  theme_minimal() +
  theme(text = element_text(family="ITC Officina Sans LT Book"),
        plot.background = element_rect(fill = "#343E48", color ="#343E48" ),
        panel.grid = element_line(color = "grey"),
        plot.title = element_text(colour = "grey", hjust = .5))

map
```

```{r}
p2 <-
  (map|p1) +
  plot_annotation(
  title = 'HISTORY OF HUMANS IN SPACE \n',
  caption = 'Source: M. Stavnichuk & T. Corlett (https://doi.org/10.1016/j.lssr.2020.06.003)\nwww.fishwongy.com') & 
  theme(text = element_text('IBM Plex Sans SemiBold', colour = "#F5F5F5"),
        plot.title = element_text(size = 26, hjust = .5),
        plot.caption = element_text(size = 15, family = "ITC Officina Sans LT Book"),
        plot.margin = unit(c(1,1,1,1), "cm"),
        plot.background = element_rect(fill = "#343E48")) 

ggsave("photo/space_patch.png", p2, dpi = 320, width = 25, height = 15)
```

#Plot 2
```{r}
library(tidyverse)
library(hrbrthemes)
library(vegan)
library(beyonce)
library(patchwork)
library(vapoRwave)
```

```{r}
astronauts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')
```

```{r}
astronauts  <- astronauts %>%
  mutate(occupation = tolower(occupation))
```

```{r}
lengthen_pal <- function(x,shortpal){
  ncolours <- length(unique(x))
  newpal <- colorRampPalette(shortpal)(ncolours)
  return(newpal)
}
```

```{r}
palitra.pal <- c('#96ffff','#52eeff','#17d8ff','#5cbcff','#5cbcff','#a696ff','#e064e6','#ff009f')
#nb.cols <- length(levels(factor(pdat$art_viol)))
mycolors <- colorRampPalette(palitra.pal)(8)
```

```{r}
palitra <- c('#FFFFDE','#FFE9B3','#FFCC94','#FFA98C','#FF809F','#FF5AC8','#FF52FF')
pal <- rev(lengthen_pal(x = 1:8, shortpal = beyonce_palette(101)))
gpal <- beyonce_palette(104)[c(5,4)]
gpal <- beyonce_palette(74)[c(9,4)]
```

```{r}
p1 <-
astronauts %>%
  filter(eva_hrs_mission > 0) %>%
  ggplot(aes(x = year_of_mission, y = eva_hrs_mission, colour = sex)) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = 'lm') +
  scale_y_continuous(limits = c(0, 50)) +
  scale_x_continuous(breaks = seq(from = 1960, to = 2020, by = 10), 
                     labels = paste0(seq(1960, 2020, by = 10), "s")) +
  labs(x = "", y = "Extravehicular hours\n") +
  scale_colour_manual('', values = gpal) + #c("#AF7366", "#78A8D1")
  theme(legend.position = 'bottom') +
  theme_delabj_dark() +
  theme(text = element_text(family="ITC Officina Sans LT Book"),
        legend.position="top",
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(family="ITC Officina Sans LT Bold"),
        axis.text.y = element_text(family="ITC Officina Sans LT Bold"),
        #axis.title=element_text(size=20),
        plot.title = element_text(family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0, vjust = -3, family="ITC Officina Sans LT Book"),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, family="ITC Officina Sans LT Book"))

p1
```

```{r}
dtable <- astronauts %>% # diversity table
  count(mission_title, year_of_mission, nationality) %>%
  pivot_wider(names_from = nationality,
              values_from = n,
              values_fill = 0) 

divs <- data.frame(shannon = diversity(dtable[,-c(1,2)]),
                   dtable[,c(1,2)])

missions <- astronauts %>%
  distinct(mission_title, year_of_mission) %>%
  full_join(divs)
```

```{r}
p2 <- 
missions %>%
  group_by(year_of_mission,shannon) %>%
  summarize(nmissions = length(mission_title)) %>%
  filter(shannon > 0) %>%
  
ggplot(aes(x = year_of_mission, 
           y = shannon,
           size = nmissions)) +
  geom_point(colour = '#7ADCF6', alpha = 0.5) +
  scale_x_continuous(breaks = seq(from = 1960, to = 2020, by = 10), 
                     labels = paste0(seq(1960, 2020, by = 10), "s")) +
  scale_size(breaks = c(1, 2, 3)) +
  labs(x = "", y = "Diversity index of astronaut nationalities\n",
       size = "Number of missions") +
  theme_delabj_dark() +
  theme(text = element_text(family="ITC Officina Sans LT Book"),
        legend.position="top",
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(family="ITC Officina Sans LT Bold"),
        axis.text.y = element_text(family="ITC Officina Sans LT Bold"),
        #axis.title=element_text(size=20),
        plot.title = element_text(family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0, vjust = -3, family="ITC Officina Sans LT Book"),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, family="ITC Officina Sans LT Book"))

p2
```

# fct_lump() 太多row, group個other出黎
#summarise(n = n()) 一樣 count(year_of_mission, natcat) 
```{r}
singlecountrymissions <- missions %>%
  filter(shannon == 0) %>%
  left_join(astronauts %>% select(nationality,mission_title)) %>%
  mutate(natcat = fct_lump(nationality, n = 6)) %>%
  group_by(year_of_mission, natcat) %>%
  summarise(n = n())

singlecountrymissions
```

```{r}
p3 <- 
singlecountrymissions %>%
  ggplot(aes(x = year_of_mission, y = n, 
             fill = natcat, colour = natcat)) +
  geom_col() +
  scale_x_continuous(breaks = seq(from = 1960, to = 2020, by = 10), 
                     labels = paste0(seq(1960, 2020, by = 10), "s")) +
  scale_fill_manual('', values = mycolors) +
  scale_colour_manual('', values = mycolors) +
  #scale_fill_hyperBubble(name = "") +
  #vapoRwave::scale_colour_hyperBubble(name = "") +
  labs(x = "", y = "Single-country missions\n") +
  theme_delabj_dark() +
  theme(text = element_text(family="ITC Officina Sans LT Book"),
        legend.position="top",
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(family="ITC Officina Sans LT Bold"),
        axis.text.y = element_text(family="ITC Officina Sans LT Bold"),
        #axis.title=element_text(size=20),
        plot.title = element_text(family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(hjust = 0, vjust = -3, family="ITC Officina Sans LT Book"),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, family="ITC Officina Sans LT Book"))

p3
```

```{r}
png("photo/astronauts_patch.png", width = 12, height = 10, units = 'in',  res = 200)
((p2 | p1 / p3 + plot_layout(heights = c(2,1), ncol = 1))) +
  plot_layout(ncol = 2) + 
  plot_annotation(title = 'Diversity of space missions',
                  subtitle = 'Collaborative missions between countries, and gender in astronaut extravehicular hours over time',
                  caption = 'Source: M. Stavnichuk & T. Corlett (https://doi.org/10.1016/j.lssr.2020.06.003)\nwww.fishwongy.com') &  
  theme(text = element_text('ITC Officina Sans LT Bold', colour = "#F5F5F5"),
        plot.title = element_text(size = 26, hjust = .5),
        plot.subtitle = element_text(hjust =  .5),
        plot.caption = element_text(size = 15, family = "ITC Officina Sans LT Book"),
        plot.margin = unit(c(1,1,1,1), "cm"),
        plot.background = element_rect(fill = "#343E48")) 
dev.off()
```


#Table
```{r}
astronauts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')
```

```{r}
astro_table <- astronauts %>% 
  mutate(decade = year_of_mission %/% 10 * 10) %>% 
	group_by(name, decade) %>% 
  add_count(name = "decade_missions") %>% 
  ungroup() %>% 
  filter(sex == "female") %>%
  distinct(year_of_birth, name, total_number_of_missions, total_hrs_sum, total_eva_hrs, year_of_mission, decade, decade_missions) %>% 
  mutate(
    name = fct_reorder(name, total_hrs_sum),
    total_hrs_sum = round(total_hrs_sum),
    total_eva_hrs = round(total_eva_hrs, 1)
  ) %>% 
  #arrange(-total_hrs_sum) %>%
  filter(total_hrs_sum > 4000)

colorbar <- data.frame(name = "colorbar", decade = seq(1960, 2010, by = 10), decade_missions = 1:6)
```

```{r, fig.width=7, fig.height=10}
ggplot(astro_table) +
# bars --------------------------------------------------------------------
  geom_tile(aes(1985, name, height = 0.4, width = 60), fill = "grey95") +
  geom_tile(aes(decade, name, fill = decade_missions, height = 0.39)) +
	annotate("text", 1985, 12.6, label = "'70\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\'10",
	         colour = "grey70", family =  "ITC Officina Sans LT Book", vjust = 0, lineheight = 0.8, size = 1.5) +
# text rows ---------------------------------------------------------------
  geom_text(aes(1555, name, label = name), hjust = 0, family =  "ITC Officina Sans LT Bold", 
            colour = "black", size = 3.8, check_overlap = TRUE) +
  geom_text(aes(1740, name, label = year_of_birth), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "grey70", size = 3.5, check_overlap = TRUE) +
  geom_text(aes(1810, name, label = total_hrs_sum), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "black", size = 3.5, check_overlap = TRUE) +
  geom_text(aes(1875, name, label = total_eva_hrs), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "black", size = 3.5, check_overlap = TRUE) +
  geom_text(aes(1925, name, label = total_number_of_missions), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "black", size = 3.5, check_overlap = TRUE) +
# column titles -----------------------------------------------------------
  annotate("text", 1740, 13.8, label = toupper("year of\nbirth"), colour = "grey60", family = "ITC Officina Sans LT Book", hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
  annotate("text", 1810, 13.8, label = toupper("total mission\nhours"), colour = "grey60", family =  "ITC Officina Sans LT Book", hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
  annotate("text", 1875, 13.8, label = toupper("total eva\nhours"), colour = "grey60", family =  "ITC Officina Sans LT Book", hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
  annotate("text", 1925, 13.8, label = toupper("total\nmissions"), colour = "grey60", family =  "ITC Officina Sans LT Book", hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
# stars -------------------------------------------------------------------
  geom_text(data = subset(astro_table, total_hrs_sum == max(astro_table$total_hrs_sum)), aes(1775, name, label = "★"), family = "Apple Symbols", colour = "darkgoldenrod1") +
  geom_text(data = subset(astro_table, total_eva_hrs == max(astro_table$total_eva_hrs)), aes(1845, name, label = "★"), family = "Apple Symbols", colour = "darkgoldenrod1") +
  geom_text(data = subset(astro_table, total_number_of_missions == max(astro_table$total_number_of_missions)), aes(1910, name, label = "★"), family = "Apple Symbols", colour = "darkgoldenrod1") +
# table lines -------------------------------------------------------------
  geom_hline(yintercept = seq(0.5, 13.5, by = 1), size = 0.25, colour = "grey70") +
# colorbar ----------------------------------------------------------------
  annotate("text", 1985, 14.7, label = toupper("missions\nper decade"), colour = "grey60", 
           family =  "ITC Officina Sans LT Book", lineheight = 0.8, size = 2.5) +
  geom_tile(data = colorbar, aes(decade, 14.2, fill = decade_missions, height = 0.25)) +
  annotate("text", 1985, 13.6, label = toupper("fewer\t\t\tmore"), colour = "grey60", 
           family =  "ITC Officina Sans LT Book", vjust = 0, lineheight = 0.8, size = 2.5) +
# scales, theme, etc ------------------------------------------------------
  coord_fixed(ratio = 20, clip = "off") +
  scale_x_continuous(limits = c(1555, 2015), expand = c(0, 0)) +
  scale_fill_gradient(low = "lightskyblue1", high = "purple4") +
	labs(
		title = "Female astronauts with more than 4000 mission hours",
		caption = "Source: M. Stavnichuk & T. Corlett (https://doi.org/10.1016/j.lssr.2020.06.003)\nwww.fishwongy.com"
		) +
  theme_void() +
  theme(
    legend.position = "none",
    plot.margin = margin(10, 5, 10, 5),
		plot.title = element_text(family =  "ITC Officina Sans LT Bold", margin = margin(0, 0, 15, 0)),
		plot.caption = element_text(family =  "ITC Officina Sans LT Book", hjust = 0, size = 6.5, colour = "grey70")
  ) +
  ggsave("photo/astronauts_table.png", dpi = 320, width = 7, height = 10)
  
NULL
```


```{r, fig.width=7, fig.height=10}
ggplot(astro_table) +
# bars --------------------------------------------------------------------
  geom_tile(aes(1985, name, height = 0.4, width = 60), fill = "#4e5d6b") +
  geom_tile(aes(decade, name, fill = decade_missions, height = 0.39)) +
	annotate("text", 1985, 12.6, label = "'70\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\'10",
	         colour = "#F5F5F5", family =  "ITC Officina Sans LT Book", vjust = 0, lineheight = 0.8, size = 1.5) +
# text rows ---------------------------------------------------------------
  geom_text(aes(1555, name, label = name), hjust = 0, family =  "ITC Officina Sans LT Bold", 
            colour = "#F5F5F5", size = 3.8, check_overlap = TRUE) +
  geom_text(aes(1740, name, label = year_of_birth), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "#F5F5F5", size = 3.5, check_overlap = TRUE) +
  geom_text(aes(1810, name, label = total_hrs_sum), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "#F5F5F5", size = 3.5, check_overlap = TRUE) +
  geom_text(aes(1875, name, label = total_eva_hrs), hjust = 1, family =  "ITC Officina Sans LT Book", 
            colour = "#F5F5F5", size = 3.5, check_overlap = TRUE) +
  geom_text(aes(1925, name, label = total_number_of_missions), hjust = 1, family =  "ITC Officina Sans LT Book", 
           colour = "#F5F5F5",size = 3.5, check_overlap = TRUE) +
# column titles -----------------------------------------------------------
  annotate("text", 1740, 13.8, label = toupper("year of\nbirth"),colour = "#F5F5F5", family = "ITC Officina Sans LT Book", 
           hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
  annotate("text", 1810, 13.8, label = toupper("total mission\nhours"), colour = "#F5F5F5", family =  "ITC Officina Sans LT Book", 
           hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
  annotate("text", 1875, 13.8, label = toupper("total eva\nhours"), colour = "#F5F5F5", family =  "ITC Officina Sans LT Book",
           hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
  annotate("text", 1925, 13.8, label = toupper("total\nmissions"), colour = "#F5F5F5",family =  "ITC Officina Sans LT Book",
           hjust = 1, vjust = 0, lineheight = 0.8, size = 3) +
# stars -------------------------------------------------------------------
  geom_text(data = subset(astro_table, total_hrs_sum == max(astro_table$total_hrs_sum)), aes(1775, name, label = "★"), family = "Apple Symbols", colour = "darkgoldenrod1") +
  geom_text(data = subset(astro_table, total_eva_hrs == max(astro_table$total_eva_hrs)), aes(1845, name, label = "★"), family = "Apple Symbols", colour = "darkgoldenrod1") +
  geom_text(data = subset(astro_table, total_number_of_missions == max(astro_table$total_number_of_missions)), aes(1910, name, label = "★"), family = "Apple Symbols", colour = "darkgoldenrod1") +
# table lines -------------------------------------------------------------
  geom_hline(yintercept = seq(0.5, 13.5, by = 1), size = 0.25, colour = "grey70") +
# colorbar ----------------------------------------------------------------
  annotate("text", 1985, 14.7, label = toupper("missions\nper decade"), colour = "#F5F5F5",
           family =  "ITC Officina Sans LT Book", lineheight = 0.8, size = 2.5) +
  geom_tile(data = colorbar, aes(decade, 14.2, fill = decade_missions, height = 0.25)) +
  annotate("text", 1985, 13.6, label = toupper("fewer\t\t\tmore"), colour = "#F5F5F5",
           family =  "ITC Officina Sans LT Book", vjust = 0, lineheight = 0.8, size = 2.5) +
# scales, theme, etc ------------------------------------------------------
  coord_fixed(ratio = 20, clip = "off") +
  scale_x_continuous(limits = c(1555, 2015), expand = c(0, 0)) +
  scale_fill_gradient(low = "lightskyblue1", high = "purple4") +
	labs(
		title = "<b, style = 'color:#FFD900'>Female astronauts</b> with more than <b, style = 'color:#e3cd4f'>4000</b> mission hours",
		caption = "Source: M. Stavnichuk & T. Corlett (https://doi.org/10.1016/j.lssr.2020.06.003)\nwww.fishwongy.com"
		) +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "#343E48", color = "#343E48"),
    plot.margin = margin(10, 5, 10, 5),
		plot.title = element_markdown(family =  "ITC Officina Sans LT Bold", margin = margin(0, 0, 15, 0), colour = "#F5F5F5",),
		plot.caption = element_text(family =  "ITC Officina Sans LT Book", hjust = 0, size = 6.5,colour = "#F5F5F5",)
  ) +
  ggsave("photo/astronauts_table_dark.png", dpi = 320, width = 7, height = 10) +
  
NULL
```

