```{r}
library(readr)
library(ggplot2)
library(delabj)
library(ggtext)
library(paletteer)
library(evoPalette)
library(ghibli)
library(patchwork)
library(tidyverse)
library(ggrepel)
```


```{r}
anime <- read_csv(file="https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-23/tidy_anime.csv")
```

```{r}
anime$year <- as.numeric(substr(anime$start_date, 1,4))
anime <- anime %>% 
            select(1:4, 6:10, 14, 18,20,21, 29)  %>%
            #mutate(year = as.numeric(year)) %>%
            mutate(decade = year - year %% 10)
```

```{r}
producer <- anime %>%
  group_by(producers) %>% 
               count(producers) %>%
               ungroup() %>%
 # mutate_at(c("producers"), as.factor) %>%
  drop_na(producers)%>%
  arrange(-n) 
```

```{r}
pro_yr <- anime %>%
  group_by(producers, decade) %>% 
  count(producers, decade) %>%
  ungroup() %>%
  #mutate_at(c("producers"), as.factor) %>%
  drop_na(producers, decade)%>%
  arrange(decade) %>%
  filter(producers %in% c("TV Tokyo", "Aniplex", "Bandai Visual", "NHK", "Fuji TV", "Sotsu", "Dentsu", "Square Enix",
                          "AT-X","Kadokawa Shoten", "TBS"))
```

#Plot for producer
```{r}
p1 <-
producer %>%
  top_n(10) %>%
  
ggplot(aes(x = reorder(producers, n), y = n)) + 
  geom_col(fill = "#729ec4") + #position = "dodge", #83B692
  theme_delabj_dark() + 
  scale_y_continuous(position = "right") +
  geom_text(aes(y = n, label = n), size = 12, nudge_y = -100, color = "white", family="ITC Officina Sans LT Book") +
  theme(text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 25),
        axis.text.y = element_text(size = 25),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 36, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 25),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 15)) +
  labs(x = "", y = "", 
       title = "Top 10  <b, style = 'color:#729ec4'>Anime Producer\n",
       subtitle = "Number of anime produced by each producing company",
       caption = "") + #Data: Tidy Tuesday\nwww.fishwongy.com
    coord_flip() +
#  ggsave("producer.png", width = 18, height = 10, dpi = 320) +
NULL

p1
```

#Producer and year
```{r, fig.height=12, fig.width=16}
py1 <- 
pro_yr %>% 
  ggplot(aes(decade, n, fill = producers)) +
  geom_bar(stat = 'identity') +
  scale_y_continuous(expand = expansion(0,0)) + #breaks = seq(from = 0, to =10, by = 2), labels = seq(0, 10, by = 2), expand = expansion(0,0)
  scale_x_continuous(breaks = seq(from = 1950, to =2010, by = 10), labels = paste0(seq(1950, 2010, by = 10), "s")) +
  scale_fill_paletteer_d("dutchmasters::view_of_Delft") +
  #scale_fill_ghibli_d("LaputaLight", direction = -1) +
  #scale_fill_evo("Tangela") +
  labs(title = "Top  <b, style = 'color:#729ec4'>Anime Producers</b> Throughout the Decades\n", 
       subtitle = "Number of anime produced",
       x = "", y = "",
       caption = "Data: Tidy Tuesday\nwww.fishwongy.com") +
  theme_delabj_dark() +
  theme(text = element_text(family = "IBM Plex Sans SemiBold", size = 13),
                      title = element_text("IBM Plex Sans SemiBold", size = 24),
                      plot.title = element_markdown("IBM Plex Sans SemiBold", size = 36),
                      plot.title.position = "plot",
                      plot.subtitle = element_text("IBM Plex Sans SemiBold", size = 25),
                      plot.caption = element_text(size = 20),
                      plot.caption.position = "plot",
                      axis.text = element_text(size = 20, color = "#F5F5F5"),
                      #axis.text.x = element_blank(),
                      axis.line.x = element_line(color = "#F5F5F5"),
                      axis.line.y = element_line(color = "#F5F5F5"),
                      #axis.line.x = element_blank(),
                      #axis.line.y = element_line(color = "gray80"),
                      #panel.grid = element_blank(),
                      legend.text = element_text(size = 18, family = "IBM Plex Sans Medium"),
                      legend.title = element_blank(),
                     # legend.background = element_rect(fill = "#525252", color = "#525252"),
                      plot.margin = margin(20, 20, 20, 20),
                      panel.grid.major.x = element_blank(),
                      panel.grid.minor.x = element_blank(),
                     # panel.grid.major.y = element_line(color = "gray70"),
                      panel.grid.minor.y = element_blank(),
                      #plot.background = element_rect(fill = "#525252", color = "#525252"),
                      legend.position = c(.2, .725)) +
  #ggsave("black-achievements.png", width = 24, height = 12, dpi = 320) +
NULL

py1
```

```{r}
(p1 / py1) +
   ggsave("photo/producer_patch.png", dpi = 320, width = 18, height = 23)
```

#Aggregate mean score 
```{r}
pro_s <- anime %>% 
            select(7, 11) %>%
            drop_na() %>%
            group_by(producers) %>%
            summarise(mean = mean(score)) %>%
            mutate(mean = round(mean, 2)) %>%
            #filter(studio %in% c("TV Tokyo", "Aniplex", "Bandai Visual", "NHK", "Fuji TV", "Sotsu", "Dentsu", "Square Enix",
                         # "AT-X","Kadokawa Shoten", "TBS")) %>%
            left_join(producer, by = "producers") %>%
            arrange(-mean)

pro_s
```

```{r}
p2 <-
pro_s %>%
  filter(producers %in% c("TV Tokyo", "Aniplex", "Bandai Visual", "NHK", "Fuji TV", "Sotsu", "Dentsu", "Square Enix",
                          "AT-X","Kadokawa Shoten", "TBS")) %>%
  
ggplot(aes(x = reorder(producers, mean), y = mean)) + 
  geom_col(fill = "#729ec4") + #position = "dodge", #83B692
  theme_delabj_dark() + 
  scale_y_continuous(position = "right") +
  geom_text(aes(y = mean, label = mean),  nudge_y = -.4, size = 12, color = "white", family="ITC Officina Sans LT Book") +
  theme(text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 25),
        axis.text.y = element_text(size = 25),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 36, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 25),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 15)) +
  labs(x = "", y = "", 
       title = "Top 10 <b, style = 'color:#729ec4'>Anime Producer\n",
       subtitle = "Mean anime score rated by viewer",
       caption = "") + #Data: Tidy Tuesday\nwww.fishwongy.com
    coord_flip() +
#  ggsave("black-gender.png", width = 18, height = 10, dpi = 320) +
NULL
p2
```

```{r}
ps1 <- 
pro_s %>%
  ggplot(aes(x = n, y = mean)) + 
  geom_point(stat = 'identity', group = 1, color = "#729ec4", size = 3) +
  geom_point(data = pro_s %>% filter(producers %in% c("TV Tokyo", "Aniplex", "Bandai Visual", "NHK", "Square Enix", "Dentsu")), 
             aes(x = n, y = mean), colour="#AF7366", size = 3) +
  geom_point(data = pro_s %>% filter(producers %in% c("voque ting","Miracle Robo")), 
             aes(x = n, y = mean), colour="#D5BF98", size = 3) +
  #geom_point(color = ifelse(studio %in% c("Toei Animation", "Sunrise", "J.C.Staff" , "Madhouse", "Studio Deen", 
                                              #"Production I.G", "A-1 Pictures", "Studio Pierrot","Xebec", "TBS"), '#721121', '#729ec4')) +
  geom_smooth(method = "lm", se = FALSE, color = "#F5F5F5", alpha = 0.5, size = 0.7) +
  theme_delabj_dark() +
  geom_text_repel(data = pro_s %>% filter(producers %in% c("TV Tokyo", "Aniplex", "Bandai Visual", "NHK", "Square Enix", "Dentsu")),
            aes(label = producers), color = "#bd7d6f", vjust = "inward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
            family="ITC Officina Sans LT Bold", size = 10) +
   geom_text_repel(data = pro_s %>% filter(producers %in% c("voque ting","Miracle Robo")),
            aes(label = producers), color = "#D5BF98", vjust = "outward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
            family="ITC Officina Sans LT Bold", size = 10) +
  #delabj::scale_color_delabj(name = "") +
  #scale_colour_viridis_d(option = "inferno",name = "") +
 # geom_text(data = dta %>% filter(country %in% c("France", "Spain", "China", "US", "Korea", "Australia", "Iran", "Taiwan", "Brazil", "Mexico", "Singapore", "Portugal", "Indonesia")),
  #          aes(label = country), color = "black", vjust = "inward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
   #         family="ITC Officina Sans LT Book", size = 4) +
  scale_x_log10(limits = c(1, 2000)) +
  scale_y_continuous(position = "right") +
   #             breaks = c(10, 1000, 100000), labels = c("10", "1,000", "100,000")) +

  theme(text = element_text(size = 9.5, family="ITC Officina Sans LT Bold"),
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=20),
        axis.text.y = element_text(size=20),
        axis.title=element_text(size=20),
        plot.title = element_text(size = 36, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(size = 25, hjust = 0.985, vjust = -6),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, size = 21, family="ITC Officina Sans LT Book")) +
    labs(y=" ", 
        x = "\nNumber of anime produced\n", 
       title = "The More the Better?",
       subtitle = "Mean score",
      caption = "Sources: Tidy Tuesday\nwww.fishwongy.com") 
  #ggsave("photo/studio.png", width = 14, height = 10, dpi = 320) 

ps1
```

```{r}
(p2 / ps1) +
   ggsave("photo/producer_score_patch.png", dpi = 320, width = 18, height = 23)
```

#For STUDIO
```{r}
studio <- anime %>%
  group_by(studio)  %>% 
  count(studio) %>%
  ungroup() %>%
 # mutate_at(c("studio"), as.factor) %>%
  drop_na(studio)%>%
  arrange(-n) #%>%
  #top_n(10)
```

```{r}
stu_yr <- anime %>%
  group_by(studio, decade) %>% 
  count(studio, decade) %>%
  ungroup() %>%
  #mutate_at(c("producers"), as.factor) %>%
  drop_na(studio, decade)%>%
  arrange(decade) %>%
  filter(studio %in% c("Toei Animation", "Sunrise", "J.C.Staff" , "Madhouse", "Studio Deen", "Production I.G", "A-1 Pictures", "Studio Pierrot", 
                       "Xebec", "TBS"))
```

```{r}
s1 <-
studio %>%
  top_n(10) %>%
  
ggplot(aes(x = reorder(studio, n), y = n)) + 
  geom_col(fill = "#729ec4") + #position = "dodge", #83B692
  theme_delabj_dark() + 
  scale_y_continuous(position = "right") +
  geom_text(aes(y = n, label = n), size = 12, nudge_y = -150, color = "white", family="ITC Officina Sans LT Book") +
  theme(text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 25),
        axis.text.y = element_text(size = 25),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 36, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 25),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 15)) +
  labs(x = "", y = "", 
       title = "Top 10  <b, style = 'color:#729ec4'>Anime Studio\n",
       subtitle = "Number of anime produced by each studio",
       caption = "") + #Source: MyAnimeList\nwww.fishwongy.com
    coord_flip() +
#  ggsave("black-gender.png", width = 18, height = 10, dpi = 320) +
NULL

s1
```

```{r}
sy1 <- 
stu_yr %>% 
  ggplot(aes(decade, n, fill = studio)) +
  geom_bar(stat = 'identity') +
  scale_y_continuous(breaks = seq(from = 0, to = 8000, by = 2000), labels = seq(0, 8000, by = 2000), expand = expansion(0,0)) + 
  #breaks = seq(from = 0, to =10, by = 2), labels = seq(0, 10, by = 2), expand = expansion(0,0)
  scale_x_continuous(breaks = seq(from = 1950, to =2010, by = 10), labels = paste0(seq(1950, 2010, by = 10), "s")) +
  scale_fill_paletteer_d("dutchmasters::view_of_Delft") +
  #scale_fill_ghibli_d("LaputaLight", direction = -1) +
  #scale_fill_evo("Tangela") +
  labs(title = "Top  <b, style = 'color:#729ec4'>Anime Studio</b> Throughout the Decades\n", 
       subtitle = "Number of anime produced",
       x = "", y = "",
       caption = "Source: MyAnimeList\nwww.fishwongy.com") +
  theme_delabj_dark() +
  theme(text = element_text(family = "IBM Plex Sans SemiBold", size = 13),
                      title = element_text("IBM Plex Sans SemiBold", size = 24),
                      plot.title = element_markdown("IBM Plex Sans SemiBold", size = 36),
                      plot.title.position = "plot",
                      plot.subtitle = element_text("IBM Plex Sans SemiBold", size = 25),
                      plot.caption = element_text(size = 20),
                      plot.caption.position = "plot",
                      axis.text = element_text(size = 20, color = "#F5F5F5"),
                      #axis.text.x = element_blank(),
                      axis.line.x = element_line(color = "#F5F5F5"),
                      axis.line.y = element_line(color = "#F5F5F5"),
                      #axis.line.x = element_blank(),
                      #axis.line.y = element_line(color = "gray80"),
                      #panel.grid = element_blank(),
                      legend.text = element_text(size = 18, family = "IBM Plex Sans Medium"),
                      legend.title = element_blank(),
                     # legend.background = element_rect(fill = "#525252", color = "#525252"),
                      plot.margin = margin(20, 20, 20, 20),
                      panel.grid.major.x = element_blank(),
                      panel.grid.minor.x = element_blank(),
                     # panel.grid.major.y = element_line(color = "gray70"),
                      panel.grid.minor.y = element_blank(),
                      #plot.background = element_rect(fill = "#525252", color = "#525252"),
                      legend.position = c(.15, .825)) +
  #ggsave("black-achievements.png", width = 24, height = 12, dpi = 320) +
NULL

sy1
```

```{r}
(s1 / sy1) +
   ggsave("photo/studio_patch.png", dpi = 320, width = 18, height = 23)
```

#Aggregate mean score 
```{r}
stu_s <- anime %>% 
            select(9, 11) %>%
            drop_na() %>%
            group_by(studio) %>%
            summarise(mean = mean(score)) %>%
            mutate(mean = round(mean, 2)) %>%
            #filter(studio %in% c("Toei Animation", "Sunrise", "J.C.Staff" , "Madhouse", "Studio Deen", "Production I.G", 
             #                    "A-1 Pictures", "Studio Pierrot", "Xebec", "TBS")) %>%
            left_join(studio, by = "studio") %>%
            arrange(-mean)

stu_s
```

```{r}
s2 <-
stu_s %>%
  filter(studio %in% c("Toei Animation", "Sunrise", "J.C.Staff" , "Madhouse", "Studio Deen", "Production I.G", 
                                 "A-1 Pictures", "Studio Pierrot", "Xebec", "TBS")) %>%
  
ggplot(aes(x = reorder(studio, mean), y = mean)) + 
  geom_col(fill = "#729ec4") + #position = "dodge", #83B692
  theme_delabj_dark() + 
  scale_y_continuous(position = "right") +
  geom_text(aes(y = mean, label = mean),  nudge_y = -.4, size = 12, color = "white", family="ITC Officina Sans LT Book") +
  theme(text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 25),
        axis.text.y = element_text(size = 25),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 36, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 25),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 15)) +
  labs(x = "", y = "", 
       title = "Top 10 <b, style = 'color:#729ec4'>Anime Studio\n",
       subtitle = "Mean anime score rated by viewer",
       caption = "") + #Source: MyAnimeList\nwww.fishwongy.com
    coord_flip() +
#  ggsave("black-gender.png", width = 18, height = 10, dpi = 320) +
NULL
s2
```

```{r}
ss1 <- 
stu_s %>%
  ggplot(aes(x = n, y = mean)) + 
  geom_point(stat = 'identity', group = 1, color = "#729ec4", size = 3) +
  geom_point(data = stu_s %>% filter(studio %in% c("Toei Animation","A-1 Pictures")), 
             aes(x = n, y = mean), colour="#AF7366", size = 3) +
  geom_point(data = stu_s %>% filter(studio %in% c("Egg Firm","Shuka", "Bandai Namco Pictures")), 
             aes(x = n, y = mean), colour="#D5BF98", size = 3) +
  #geom_point(color = ifelse(studio %in% c("Toei Animation", "Sunrise", "J.C.Staff" , "Madhouse", "Studio Deen", 
                                              #"Production I.G", "A-1 Pictures", "Studio Pierrot","Xebec", "TBS"), '#721121', '#729ec4')) +
  geom_smooth(method = "lm", se = FALSE, color = "#F5F5F5", alpha = 0.5, size = 0.7) +
  theme_delabj_dark() +
  geom_text_repel(data = stu_s %>% filter(studio %in% c("Toei Animation","A-1 Pictures")),
            aes(label = studio), color = "#bd7d6f", vjust = "inward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
            family="ITC Officina Sans LT Bold", size = 10) +
   geom_text_repel(data = stu_s %>% filter(studio %in% c("Egg Firm","Shuka", "Bandai Namco Pictures")),
            aes(label = studio), color = "#D5BF98", vjust = "outward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
            family="ITC Officina Sans LT Bold", size = 10) +
  #delabj::scale_color_delabj(name = "") +
  #scale_colour_viridis_d(option = "inferno",name = "") +
 # geom_text(data = dta %>% filter(country %in% c("France", "Spain", "China", "US", "Korea", "Australia", "Iran", "Taiwan", "Brazil", "Mexico", "Singapore", "Portugal", "Indonesia")),
  #          aes(label = country), color = "black", vjust = "inward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
   #         family="ITC Officina Sans LT Book", size = 4) +
  scale_x_log10(limits = c(1, 3200)) +
  scale_y_continuous(position = "right") +
   #             breaks = c(10, 1000, 100000), labels = c("10", "1,000", "100,000")) +

  theme(text = element_text(size = 9.5, family="ITC Officina Sans LT Bold"),
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=20),
        axis.text.y = element_text(size=20),
        axis.title=element_text(size=20),
        plot.title = element_text(size = 36, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(size = 25, hjust = 0.985, vjust = -6),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, size = 21, family="ITC Officina Sans LT Book")) +
    labs(y=" ", 
        x = "\nNumber of anime produced\n", 
       title = "The More the Better?",
       subtitle = "Mean score",
      caption = "Sources: MyAnimeList\nwww.fishwongy.com") 
  #ggsave("photo/studio.png", width = 14, height = 10, dpi = 320) 

ss1
```

```{r}
(s2 / ss1) +
   ggsave("photo/studio_patch2.png", dpi = 320, width = 18, height = 23)
```

#Genre - score/ Genre - popularity
```{r}
gen_s <- anime %>% 
            select(8, 11) %>%
            drop_na() %>%
            group_by(genre) %>%
            summarise(mean_score = mean(score)) %>%
            mutate(mean_score = round(mean_score, 2)) %>%
            arrange(-mean_score)

gen_s
```

```{r}
gen_sp <- anime %>% 
            select(8, 13) %>%
            drop_na() %>%
            group_by(genre) %>%
            summarise(mean_pop = mean(popularity)) %>%
            mutate(mean_pop = round(mean_pop, 0)) %>%
            left_join(gen_s, by = "genre") %>%
            arrange(-mean_pop)

gen_sp
```

```{r}
gc1 <- 
gen_sp %>%
  ggplot(aes(x = mean_pop, y = mean_score)) + 
  geom_point(stat = 'identity', group = 1, color = "#729ec4", size = 5) +
  geom_point(data = gen_sp %>% filter(genre %in% c("Kids","Dementia", "Music", "Adventure")), 
             aes(x = mean_pop, y = mean_score), colour="#AF7366", size = 5) +
  geom_point(data = gen_sp %>% filter(genre %in% c("Thriller","Josei", "Mystery", "Psychological", "Shounen")), 
             aes(x = mean_pop, y = mean_score), colour="#D5BF98", size = 5) +
  #geom_point(color = ifelse(studio %in% c("Toei Animation", "Sunrise", "J.C.Staff" , "Madhouse", "Studio Deen", 
                                              #"Production I.G", "A-1 Pictures", "Studio Pierrot","Xebec", "TBS"), '#721121', '#729ec4')) +
  geom_smooth(method = "lm", se = FALSE, color = "#F5F5F5", alpha = 0.5, size = 0.7) +
  theme_delabj_dark() +
  geom_text_repel(data = gen_sp %>% filter(genre %in% c("Kids","Dementia", "Music", "Adventure")),
            aes(label = genre), color = "#bd7d6f", vjust = "inward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
            family="ITC Officina Sans LT Bold", size = 10) +
   geom_text_repel(data = gen_sp %>% filter(genre %in% c("Thriller","Josei", "Mystery", "Psychological", "Shounen")),
            aes(label = genre), color = "#D5BF98", vjust = "outward", hjust = "inward",  #nudge_y = 0.2, nudge_x = 0, 
            family="ITC Officina Sans LT Bold", size = 10) +
  #delabj::scale_color_delabj(name = "") +
  #scale_colour_viridis_d(option = "inferno",name = "") +
  #scale_x_log10(limits = c(1200, 12000)) +
  scale_y_continuous(position = "right") +
   #             breaks = c(10, 1000, 100000), labels = c("10", "1,000", "100,000")) +

  theme(text = element_text(size = 9.5, family="ITC Officina Sans LT Bold"),
        axis.line = element_blank(), 
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(size=20),
        axis.text.y = element_text(size=20),
        axis.title=element_text(size=20),
        plot.title = element_markdown(size = 40, family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_text(size = 25, hjust = 0.985, vjust = 0),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, size = 21, family="ITC Officina Sans LT Book")) +
    labs(y=" ", 
        x = "\nAverage popularity\n", 
       title = "Anime <b, style = 'color:#bd7d6f'>popularity</b> v. <b, style = 'color:#D5BF98'>rated score",
       subtitle = "Mean score",
      caption = "") #Sources: MyAnimeList\nwww.fishwongy.com
  #ggsave("photo/studio.png", width = 14, height = 10, dpi = 320) 

gc1
```

```{r}
gp1 <-
gen_sp %>%
  slice_max(mean_pop, n = 10) %>%
  
ggplot(aes(x = reorder(genre, mean_pop), y = mean_pop)) + 
  geom_col(fill = "#729ec4") + #position = "dodge", #83B692
  theme_delabj_dark() + 
  scale_y_continuous(position = "right") +
  geom_text(aes(y = mean_pop, label = mean_pop), size = 12, nudge_y = -1500, color = "white", family="ITC Officina Sans LT Book") +
  theme(text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 25),
        axis.text.y = element_text(size = 25),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 36, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 25),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 25)) +
  labs(x = "", y = "", 
       title = "Top 10  <b, style = 'color:#bd7d6f'>Popular</b> Anime genre\n",
       subtitle = "",
       caption = "Source: MyAnimeList\nwww.fishwongy.com\n") + #Source: MyAnimeList\nwww.fishwongy.com
    coord_flip() +
#  ggsave("black-gender.png", width = 18, height = 10, dpi = 320) +
NULL

gp1
```

```{r}
gs1 <-
gen_sp %>%
  slice_max(mean_score, n = 10) %>%
  
ggplot(aes(x = reorder(genre, mean_score), y = mean_score)) + 
  geom_col(fill = "#729ec4") + #position = "dodge", #83B692
  theme_delabj_dark() + 
  scale_y_continuous(position = "right") +
  geom_text(aes(y = mean_score, label = mean_score), size = 12, nudge_y = -1, color = "white", family="ITC Officina Sans LT Book") +
  theme(text = element_text( family="ITC Officina Sans LT Book", size = 13),
        panel.grid.major = element_line(color = "white", size = 0.3), 
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x.top = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(family = "ITC Officina Sans LT Bold", size = 25),
        axis.text.y = element_text(size = 25),
        #axis.text.y = element_text(size = 10, family = "ITC Officina Sans LT Bold"),
        plot.title = element_markdown(hjust = 0, vjust=-0.12, size = 36, 
                                  family="ITC Officina Sans LT Bold"),
        plot.subtitle = element_markdown(hjust = 0, vjust=-1.5, size = 25),
       plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0, vjust = -2.5, size = 15)) +
  labs(x = "", y = "", 
       title = "Top 10  <b, style = 'color:#D5BF98'>Rated</b> Anime genre\n",
       subtitle = "",
       caption = "") + #Source: MyAnimeList\nwww.fishwongy.com
    coord_flip() +
#  ggsave("black-gender.png", width = 18, height = 10, dpi = 320) +
NULL

gs1
```

