**Package**
```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lubridate)
library(scales)
library(readr)
library(quanteda)
library(delabj)
library(ggtext)
library(ghibli)
library(patchwork)
#library(cowplot)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(rgeos)
# library(geonames)
# library(countrycode)
library(rworldmap)
library(patchwork)
library(ggtext)
library(RcppRoll)
library(ggforce)
library(geofacet)
library(ggnewscale)
library(tidytuesdayR)
```
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 32)
energy_types <- tuesdata$energy_types

energy_types <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/energy_types.csv')
```
```{r}
energy_clean <- energy_types %>% 
  filter(level == "Level 1") %>%
  gather(year, n, 5:7, convert = TRUE) %>% 
  select(-level) %>% 
  mutate(
    country_name = case_when(
      country == "EL" ~ "Greece",
      country == "UK" ~ "United Kingdom",
      TRUE ~ country_name
    ),
    gtype = case_when(
      !type %in% c("Nuclear", "Conventional thermal") ~ "Renewable",
      TRUE ~ type
    )
  ) %>% 
  rename(code = country, name = country_name) %>% 
  rows_update(tibble(code = "MT", type = "Other", year = 2018, n = 172), by = c("code", "type", "year"))

energy_clean
```

```{r geofacet - grid}
eu_grid <- geofacet::eu_grid1
eu_grid[42,] <- list(row = 6, col = 10, code = "GE", name = "Georgia")
eu_grid <- eu_grid %>% 
  filter(!code %in% c("IS", "CH", "BY", "RU", "MD")) %>%
  mutate(name = ifelse(str_detect(name, "Macedonia"), "North Macedonia", name)) %>%
  drop_na()
```

```{r summary}
prop_eu <- energy_clean %>% 
  filter(year == 2018) %>% 
  group_by(name) %>% 
  summarise(
    total = sum(n),
    p_clean = sum(n[gtype != "Conventional thermal"])/total,
  )
```

```{r}
data_plot <- energy_clean %>% 
  filter(year == 2018) %>% 
  mutate(
    code = recode(code, "UK" = "GB", "EL" = "GR")
  ) %>% 
  count(code, name , year, gtype, wt = n) %>% 
  group_by(code) %>% 
  mutate(p = n/sum(n)) %>% 
  ungroup() %>% 
  left_join(prop_eu)

data_plot
```

```{r pies plot}
pies <- 
  data_plot %>% 
  ggplot() +
    aes(x0 = 0, y0 = 0) +
    stat_pie(
      aes(r0 = 0.7, r = 1, amount = p, fill = gtype),
      color = "white",
      size = 1,
      show.legend = FALSE
    ) +
    scale_fill_manual(
      values = c("#ECBA82", "#2E933C", "#81C14B")
    ) +
    new_scale_fill() +
    geom_circle(
      aes(r = 0.675, fill = p_clean),
      color = NA
    ) +
    scale_fill_fermenter(
      type = "div", 
      direction = 1,
      labels = c("25%", "50%", "75%"),
      guide = guide_colorsteps(
        title = "Clean Energy Share", 
        title.position = "top"
      )
    ) +
    geom_text(
      aes(x = 0, y = 0, label = str_glue("{comma(total, .01)}\nGWh")), 
      color = "white",
      family = "ITC Officina Sans LT Book"
    ) +
    coord_fixed() +
    facet_geo(~code, grid = eu_grid, label = "name") +
    theme_void(base_family = "IBM Plex Sans") +
    theme(
      strip.text = element_text(
        size = 16,
        margin = margin(t = 10, b = 10)
      ),
      legend.position = "bottom",
      legend.title = element_text(hjust = 0.5, size = 16),
      legend.key.width = grid::unit(15, "mm"),
      legend.key.height = grid::unit(3, "mm"),
      legend.text = element_text(size = 14)
    )
    
piesG <- ggplotGrob(pies + theme(legend.position = "none"))
legendG <- cowplot::get_legend(pies)
```

```{r notes}
notes <- tribble(
  ~x, ~y, ~label,
  0, -4.5, "**Albania** is dependent on hydroelectricity, with a share in its production of 100%. Still, its topography has the potential to supply power from wind, sun, and soil.",
  -3, 0.5, "**France** is the second largest producer of energy in the region, and has the largest share of nuclear electricity (71.3%) in the world.", 
  1, 1.75, "**Germany** is the country that produced the most energy in 2018, 12.6% was nuclear energy and 31.3% renewable energy.",
  -0.5, 3.15, "Much of **Norway**'s electricity is generated from hydropower (95%) due to the natural advantage of its topography with abundant valleys and steep rivers.", 
  4, 0.5, "**Montenegro** leads the energy transition in the region. In 2018 the production of clean energy increased by more than 100%, compared to the previous year."
)
```

```{r plot}
plot <- qplot() +
  geom_curve(
    aes(x = 1.5, y = -3.25, xend = 4, yend = 0.16), 
    size = 2, 
    curvature = 0.3, 
    color = "white", 
    lineend = "round"
  ) +
  annotation_custom(
    piesG,
    xmin = -5, xmax = 5,
    ymin = -5, ymax = 5
  ) +
  annotation_custom(
    legendG,
    xmin = -5, xmax = -2.2,
    ymin = -3.5, ymax = -3
  ) +
  geom_textbox(
    data = notes,
    aes(x, y, label = label),
    family = "ITC Officina Sans LT Book",
    lineheight = 1.5,
    # halign = 0,
    width = 0.14,
    box.color = NA,
    fill = NA,
  ) +
  geom_textbox(
    aes(
      x = -5, y = 5, 
      label = "<span style='font-size:42pt'>Clean Energy Producers, 2018</span>
  <br><br>
  <span style='font-size:15pt'>Total net energy produced (GWh) by european countries in 2018, and its distribution by <b style='color:#ECBA82'>conventional thermal</b>, <b style='color:#2E933C'>nuclear</b> and <b style='color:#81C14B'>renewable</b> energy.</span>
  <br><br>
  <i style='font-size:10pt;color:#737373;'>**GWh**: Energy generated or consumed by 1 GW of power for one hour.<br>
**How Much Power is 1 GW?** 110 Million LEDs, on typical performance.</i>"
    ),
    family = "ITC Officina Sans LT Book",
    width = unit(27, "lines"),
    lineheight = 2,
    hjust = 0,
    vjust = 1,
    fill = NA,
    box.color = NA,
  ) +
  scale_x_continuous(limits = c(-5,5), breaks = -5:5) +
  scale_y_continuous(limits = c(-5,5), breaks = -5:5) +
  labs(caption = "Source: Eurostat") +
  # theme_light() +
  theme_void() +
  theme(
    plot.caption = element_text(
        hjust = 0.5,
        size = 10,
        family = "ITC Officina Sans LT Book",
        margin = margin(b = 30)
      ),
    plot.background = element_rect(fill = "#f0f0f0", color = NA)
  )
  
ggsave("photo/plot.pdf", plot, width = 20, height = 25, device = cairo_pdf)
plot
```


#plot 2
```{r}
library(tidyverse)
library(tidytuesdayR)
library(magrittr)
library(sf)
library(rnaturalearth)
library(ggtext)
```

```{r}
df_energy <- tt_load_gh(last_tuesday()) %>% 
  tt_download() %>% 
  extract2(1)
```

```{r}
# check
df_energy %>% 
  distinct(type)
```

# CLEAN --- 
```{r}
df_energy_tidy <- df_energy %>% 
  pivot_longer(cols = c(`2016`:`2018`),
                        names_to = "year",
                        values_to = "value") %>% 
  mutate(type = case_when(
    type == "Conventional thermal" ~ "Fossil fuels",
    type %in% c("Hydro",
                "Pumped hydro power",
                "Wind",
                "Solar",
                "Geothermal") ~ "Renewable",
    TRUE ~ type
  ))

df_energy_tidy 
```

# is Europe getting greener? ----

# define custom function
```{r}
percent_change <- function (previous, new) {
  
  x <- ((new - previous)/previous) * 100
  
  return(x)
  
}
```

# find percentage change between 2016 and 2018
```{r}
df_renewable <- df_energy_tidy %>% 
  filter(type == "Renewable") %>% 
  group_by(year, country, country_name) %>% 
  summarise(total = sum(value, na.rm = T)) %>% 
  pivot_wider(names_from = "year",
              values_from = "total",
              names_prefix = "total_") %>% 
  mutate(change = percent_change(total_2016, total_2018)) %>% 
  arrange(change %>% desc())

df_renewable
```

# MAP ----
```{r}
st_europe <- ne_countries(continent = "Europe",
                          scale = "medium",
                          returnclass = "sf") %>% 
  select(name, geometry)
```

# find mis-matches between country names - no Cyprus, Georgia or Turkey on map
```{r}
df_no_match <- df_renewable %>% 
  anti_join(st_europe,
             by = c("country_name" = "name"))

df_no_match %>% 
  distinct(country_name)
```

# fix mis-matches
```{r}
df_renewable_clean <- df_renewable %>% 
  mutate(country_name = case_when(
    country_name ==  "Bosnia & Herzegovina" ~ "Bosnia and Herz.",
    country_name == "North Macedonia" ~ "Macedonia",
    country_name == "Czechia" ~ "Czech Rep.",
    country == "UK" ~ "United Kingdom",
    country == "EL" ~ "Greece",
    TRUE ~ country_name
  ))

df_renewable_clean
```

# join
```{r}
st_renewable <- df_renewable_clean %>% 
  inner_join(st_europe,
             by = c("country_name" = "name")) %>% 
  ungroup() %>%  
  st_as_sf()
```

# PLOT ----
```{r, fig.width=10, fig.height=10}
st_renewable %>% 
  ggplot() +
  geom_sf(aes(fill = change),
          size = 0.75,
          col = "white") +
  coord_sf() +
  xlim(c(-10, 40)) +
  ylim(c(35, 72)) +
  scale_fill_gradient2(low = "mediumvioletred",
                       mid = "gray55",
                       high = "lightseagreen",
                       breaks = c(-100, -50, 0, 25, 50),
                       labels = function(x) paste0(x, "%")) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 12.5),
        legend.title = element_blank(),
        plot.title = element_text(size = 30,
                                  face = "bold",
                                  margin = margin(t = 10)),
        plot.subtitle = element_markdown(size = 15),
        plot.caption = element_markdown(color = "gray30",
                                        size = 10,
                                        margin = margin(t = 20,
                                                        b = 20))) +
  guides(fill = guide_colorbar(barwidth = 25)) +
  labs(title = "Is Europe getting greener?",
       subtitle = "Percentage <b style='color:lightseagreen'>increase</b> or <b style='color:mediumvioletred'>decrease</b> of energy generated from <br> <b >renewables</b> between 2016 - 2018",
       caption = "Source: Eurostats")

```

#Plot 3
```{r}
#load packages
library(tidyverse)
library(biscale)
library(maps)
library(cowplot)
library(ggtext)
```

#load data
```{r}
country_totals <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/energy_types.csv')
```

#checking for NA's
```{r}
country_totals %>%
  count(country_name)
```

```{r}
#pivot and fix NA's
c_tot_fixed <- country_totals %>%
  pivot_longer(c('2016', '2017', '2018'),
               names_to = "year",
               values_to = "amount")%>%
  mutate(country_n = case_when(
    country == "EL" ~ "Greece",
    country == "UK" ~ "UK",
    T ~ country_name))%>%
  select(-country_name)

c_tot_fixed
```

#dropped "Other"
#specified year=2018
```{r regrouping}

v_3 <- 
  c_tot_fixed %>%
  filter(type != "Other", year == 2018) %>%
  mutate(energy_type = fct_collapse(type,
                      clean = c("Hydro","Pumped hydro power", "Wind","Solar","Geothermal"),
                      not_clean = c("Conventional thermal","Nuclear"))) %>%
  select(-type, -level, -country) %>%
  group_by(energy_type,
           country_n)%>%
  summarise(total = sum(amount)) %>%
  arrange(country_n) %>%
  pivot_wider(names_from = energy_type,
              values_from = total)%>%
  mutate(prop_clean = clean/(clean + not_clean),
         prop_not_clean = (1 - prop_clean))%>%
  select(-clean, -not_clean)

v_3
```

```{r}
pop <- read_csv("WPP2019_TotalPopulationBySex.csv")
```


#load population data
```{r}
final_df <- 
  pop %>%
  mutate(Location_1 = case_when(Location=="United Kingdom" ~ "UK",
                               T ~ Location), PopTotal = PopTotal*1000) %>%
  filter(Location_1 %in% v_3$country_n, Time == 2018) %>%
  select(Location_1, PopTotal) %>%
  left_join(v_3, by = c("Location_1"="country_n"))
```
